# Patch for frontend-web deployment in dev environment
# Only include this if deploying frontend via K8s
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-web-deployment
spec:
  replicas: 1 # Dev replica count for frontend
  template:
    spec:
      containers:
      - name: frontend-web
        env:
        - name: NODE_ENV
          value: "development"
        - name: VITE_API_URL
          value: "/api" # Assuming ingress routes /api to backend
