apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Inherit from the base configuration
resources:
- ../../base

namespace: chainocracy-dev

# Environment-specific patches or configurations
patchesStrategicMerge:
- backend-deployment-patch.yaml
- frontend-web-deployment-patch.yaml

# Add environment-specific labels
commonLabels:
  environment: dev
  tier: application

# Override image tags for dev environment
images:
- name: ${REGISTRY_URL}/chainocracy-backend
  newName: ${REGISTRY_URL}/chainocracy-backend
  newTag: dev-${BUILD_ID}
- name: ${REGISTRY_URL}/chainocracy-frontend-web
  newName: ${REGISTRY_URL}/chainocracy-frontend-web
  newTag: dev-${BUILD_ID}

# Configure resource limits for dev environment
configMapGenerator:
- name: backend-config
  behavior: merge
  literals:
  - node_env=development
  - log_level=debug
  - blockchain_node_url=http://blockchain-node-service.chainocracy-dev:26657

- name: frontend-config
  behavior: merge
  literals:
  - api_url=https://dev-api.chainocracy.io
  - environment=development
  - blockchain_node_url=https://dev-node.chainocracy.io

# Add dev-specific secrets (in a real environment, use a secret management solution)
secretGenerator:
- name: backend-secrets
  behavior: merge
  literals:
  - db_host=dev-db.chainocracy.internal
  - db_port=5432
  - db_name=chainocracy_dev
  - db_user=chainocracy_dev
  - db_password=dev_password_placeholder
  - jwt_secret=dev_jwt_secret_placeholder

- name: frontend-secrets
  behavior: merge
  literals:
  - firebase_api_key=dev_firebase_api_key
  - firebase_auth_domain=dev-chainocracy.firebaseapp.com
  - firebase_project_id=dev-chainocracy
  - firebase_storage_bucket=dev-chainocracy.appspot.com
  - firebase_messaging_sender_id=123456789
  - firebase_app_id=1:123456789:web:abcdef123456

# Configure resource patches
patches:
- path: resource-patch.yaml
  target:
    kind: Deployment
    labelSelector: "app in (chainocracy-backend, chainocracy-frontend-web)"

# Configure replicas for dev environment
replicas:
- name: backend-deployment
  count: 2
- name: frontend-web-deployment
  count: 2
